### ISSUE TITLE
HTMLBars compatibility?

### ISSUE THREAD

**Issue by Dhaulagiri** [thefrontside/ember-cli-twitter-typeahead#8]
We've been using this project with success on Ember versions prior to 1.10, but the upgrade to Ember 1.10 is causing us problems.

Until now we've had success compiling templates that are passed into the typeahead component and passing that along to the typeahead library like this:
```
templates: {
    suggestion: Handlebars.compile(this.get('suggestionTemplate')),
    <other code>
  }
```
This does not work in Ember 1.10, however, as typeahead.js throws the below error when executing this line of code:

Code:
```
$el = $(html.suggestion).append(that.templates.suggestion(suggestion)).data(datasetKey, that.name).data(valueKey, that.displayFn(suggestion)).data(datumKey, suggestion);
```
Error:
```
Uncaught TypeError:  that.templates.suggestion is not a function
```
The reason for this seems to be that with HTMLBars `that.templates.suggestion` is no longer a function but rather is an HTMLBars object.

I know this library is not under active development lately, but I was curious if anyone else had solved a similar issue?

**Comment by Dhaulagiri** [comment]
Ended up just keeping a plain handlebars dependency in the project, but it would be nice to be able to remove it
